spring:
  data:
    mongodb:
      uri: mongodb://TeamCasseb:6ipw2A9lvhhsFcD5@cluster0-shard-00-00-f5sjr.mongodb.net:27017,cluster0-shard-00-01-f5sjr.mongodb.net:27017,cluster0-shard-00-02-f5sjr.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin