package br.com.simnetwork.BotByCasseb.botDialog;

public enum StepType {
	
	SIMPLEMESSAGE,
	REQUESTCONTACT,
	REQUESTSTRING,
	REQUESTINLINEOPTION,
	REQUESTINLINEOPTIONLINK,
	INSERT,
	REQUESTCONFIRMATION,
	REQUESTRECORD,
	LINK,
	SHOWRECORD,
	INSERTDECISION,
	UPDATE,
	DELETE,
	DELAY,
	REQUESTBOOLEAN,
	REFRESH_STRUCTURE,
	ENABLE_DIALOG,
	DISABLE_DIALOG,
	SHOWALLRECORDFIELDS, 
	INSERTORUPDATE, 
	SWITCH,
	UPDATEONLY,
	DELETECONFLICTRECORD,
	DELETESELF

}
